FROM debian
LABEL maintainer 'Rodolpho rodolphoess@gmail.com'

ARG S3_BUCKET=files
ENV S3_BUCKET=${S3_BUCKET}

# S3_BUCKET sera um argumento/variavel cujo valor padrao sera files.
# S3_BUCKET sera igual ao valor do ARG S3_BUCKET.